# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# TL;DR setup:
#
# 1. brew install pre-commit
# 2. pre-commit install

fail_fast: true

repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      # Prevent giant files from being committed
      - id: check-added-large-files
      # Forbid files which have a UTF-8 byte-order marker
      - id: check-byte-order-marker
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # Ensures that (non-binary) executables have a shebang.
      - id: check-executables-have-shebangs
      # This hook checks json files for parseable syntax.
      - id: check-json
      # Check for files that contain merge conflict strings.
      - id: check-merge-conflict
      # Checks for symlinks which do not point to anything.
      - id: check-symlinks
      # This hook checks toml files for parseable syntax.
      - id: check-toml
      # This hook checks xml files for parseable syntax.
      - id: check-xml
      # This hook checks yaml files for parseable syntax.
      - id: check-yaml
      # Detects *your* aws credentials from the aws cli credentials file
      - id: detect-aws-credentials
      # Detects the presence of private keys
      - id: detect-private-key
      # Ensures that a file is either empty, or ends with one newline.
      - id: end-of-file-fixer
      # Replaces or checks mixed line ending
      - id: mixed-line-ending
      # Don't commit to branch
      - id: no-commit-to-branch
        args: ["--branch", "master"]
      # This hook sets a standard for formatting JSON files.
      - id: pretty-format-json
        args: ["--autofix"]
      # Sorts simple YAML files which consist only of top-level keys, preserving comments and blocks.
      - id: sort-simple-yaml
      # This hook trims trailing whitespace.
      - id: trailing-whitespace

  # https://github.com/golangci/golangci-lint/blob/master/.pre-commit-hooks.yaml
  - repo: git://github.com/golangci/golangci-lint
    rev: v1.17.1
    hooks:
      - id: golangci-lint
        args: ["--enable-all"]
